// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbFb_UlUHFb5JK-haNzeIf6t4Q_ih65gU',
    appId: '1:698672235915:android:030a3624f5c6235cf05b8e',
    messagingSenderId: '698672235915',
    projectId: 'p1ecapp',
    databaseURL: 'https://p1ecapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'p1ecapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG8acc_XzO2fvelovcCZANsgIg2tIf8XA',
    appId: '1:698672235915:ios:948238f2f68b9429f05b8e',
    messagingSenderId: '698672235915',
    projectId: 'p1ecapp',
    databaseURL: 'https://p1ecapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'p1ecapp.firebasestorage.app',
    iosBundleId: 'com.piec.app.piec',
  );
}
